build.version=3.0
info.app.version=3.0

accounts.message=welcome to eazybank accounts related local APIs
accounts.contactDetails.name=youssef sharaf
accounts.contactDetails.email={cipher}97fb09ecc60f16560c1a8afd12fae8e3ff32c1aab61de86dee3dbe117694d9126981d80408385f55b6077fff0a49b271
accounts.onCallSupport[0]=(555) 555-1234
accounts.onCallSupport[1]=(555) 523-1345
