build.version=2.0
info.app.version=2.0

spring.datasource.url=jdbc:mysql://host.docker.internal:3306/microstudent

accounts.message=welcome to eazybank accounts related docker database connection
accounts.contactDetails.name=youssef sharaf
accounts.contactDetails.email=youssef.m.h.sharaf@gmail.com
accounts.onCallSupport[0]=(666) 265-8565
accounts.onCallSupport[1]=(666) 523-9113


