build.version=3.0
info.app.version=3.0

accounts.message=welcome to eazybank accounts related local APIs
accounts.contactDetails.name=youssef sharaf
accounts.contactDetails.email=youssef.m.h.sharaf@gmail.com
accounts.onCallSupport[0]=(555) 555-1234
accounts.onCallSupport[1]=(555) 523-1345
