build.version=1.3

cards.message=welcome to eazybank accounts related local APIs
cards.contactDetails.name=youssef sharaf
cards.contactDetails.email=youssef.m.h.sharaf@gmail.com
cards.onCallSupport[0]=(067) 732-4982
cards.onCallSupport[1]=(746) 376-2863