build.version=1.2

cards.message=welcome to eazybank accounts related production APIs
cards.contactDetails.name=youssef sharaf
cards.contactDetails.email=youssef.m.h.sharaf@gmail.com
cards.onCallSupport[0]=(123) 937-1938
cards.onCallSupport[1]=(456) 867-1084
