build.version=1.2

loans.message= Welcome to eazyBank prod local APIs
loans.contactDetails.name= youssef sharaf
loans.contactDetails.email= youssef.m.h.sharaf@Gmail.com
loans.onCallSupport[0]=(123) 203-0171
loans.onCallSupport[1]=(456) 037-2947