build.version=1.1

loans.message= Welcome to eazyBank loans local APIs
loans.contactDetails.name= youssef sharaf
loans.contactDetails.email= youssef.m.h.sharaf@Gmail.com
loans.onCallSupport[0]=(452) 555-1234
loans.onCallSupport[1]=(546) 523-1345



