build.version=1.3

loans.message= Welcome to eazyBank qa local APIs
loans.contactDetails.name= youssef sharaf
loans.contactDetails.email= youssef.m.h.sharaf@Gmail.com
loans.onCallSupport[0]=(038) 975-8573
loans.onCallSupport[1]=(384) 465-2094